-- MySQL Script generated by MySQL Workbench
-- Son 03 Dez 2017 00:15:55 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Ferienpass
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ferienpass` ;

-- -----------------------------------------------------
-- Schema Ferienpass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ferienpass` DEFAULT CHARACTER SET utf8 ;
USE `Ferienpass` ;

-- -----------------------------------------------------
-- Table `Ferienpass`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ferienpass`.`Account` ;

CREATE TABLE IF NOT EXISTS `Ferienpass`.`Account` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(80) NOT NULL,
  `Passwort` TEXT NOT NULL,
  `Rechnungsadresse` VARCHAR(80) NOT NULL,
  `Ort` VARCHAR(50) NOT NULL,
  `PLZ` INT NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `Ferienpass`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ferienpass`.`Person` ;

CREATE TABLE IF NOT EXISTS `Ferienpass`.`Person` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Vorname` VARCHAR(50) NOT NULL,
  `Nachname` VARCHAR(50) NOT NULL,
  `Geburtsdatum` DATE NOT NULL,
  `Account_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Person_Account_idx` (`Account_ID` ASC),
  CONSTRAINT `fk_Person_Account`
    FOREIGN KEY (`Account_ID`)
    REFERENCES `Ferienpass`.`Account` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ferienpass`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ferienpass`.`Event` ;

CREATE TABLE IF NOT EXISTS `Ferienpass`.`Event` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titel` VARCHAR(80) NOT NULL,
  `Event_start` DATETIME NOT NULL,
  `Event_ende` DATETIME NOT NULL,
  `Phase_1` DATETIME NOT NULL,
  `Phase_2` DATETIME NOT NULL,
  `Anmeldeschluss` DATETIME NOT NULL,
  `visible` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ferienpass`.`Kurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ferienpass`.`Kurs` ;

CREATE TABLE IF NOT EXISTS `Ferienpass`.`Kurs` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(80) NOT NULL,
  `Beschreibung` TEXT NOT NULL,
  `Treffpunkt` VARCHAR(100) NOT NULL,
  `Teilnehmer_min` INT NULL,
  `Teilnehmer_max` INT NULL,
  `Preis_Mitglieder_rp` INT NOT NULL,
  `Preis_Nichtmitglieder_rp` INT NOT NULL,
  `Besonderes` TEXT NULL,
  `Leitung` VARCHAR(80) NOT NULL,
  `rPfad_Vorschaubild` VARCHAR(80) NULL,
  `Event_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Kurs_Event1_idx` (`Event_ID` ASC),
  CONSTRAINT `fk_Kurs_Event1`
    FOREIGN KEY (`Event_ID`)
    REFERENCES `Ferienpass`.`Event` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ferienpass`.`Klasse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ferienpass`.`Klasse` ;

CREATE TABLE IF NOT EXISTS `Ferienpass`.`Klasse` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Klassenbezeichnung` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ferienpass`.`Kurstag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ferienpass`.`Kurstag` ;

CREATE TABLE IF NOT EXISTS `Ferienpass`.`Kurstag` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Datum_Begin` DATETIME NOT NULL,
  `Datum_Ende` DATETIME NOT NULL,
  `Kurs_ID` INT NOT NULL,
  `Klasse_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Kurstag_Kurs1_idx` (`Kurs_ID` ASC),
  INDEX `fk_Kurstag_Klasse1_idx` (`Klasse_ID` ASC),
  CONSTRAINT `fk_Kurstag_Kurs1`
    FOREIGN KEY (`Kurs_ID`)
    REFERENCES `Ferienpass`.`Kurs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kurstag_Klasse1`
    FOREIGN KEY (`Klasse_ID`)
    REFERENCES `Ferienpass`.`Klasse` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ferienpass`.`KurstagTeilnehmerHelfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ferienpass`.`KurstagTeilnehmerHelfer` ;

CREATE TABLE IF NOT EXISTS `Ferienpass`.`KurstagTeilnehmerHelfer` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Teilnehmer_m` TINYINT(1) NOT NULL,
  `Helfer` TINYINT(1) NOT NULL,
  `Person_ID` INT NOT NULL,
  `Kurstag_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_KursTeilnehmerHelfer_Person1_idx` (`Person_ID` ASC),
  INDEX `fk_KurstagTeilnehmerHelfer_Kurstag1_idx` (`Kurstag_ID` ASC),
  CONSTRAINT `fk_KursTeilnehmerHelfer_Person1`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `Ferienpass`.`Person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KurstagTeilnehmerHelfer_Kurstag1`
    FOREIGN KEY (`Kurstag_ID`)
    REFERENCES `Ferienpass`.`Kurstag` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
